on:
    push:
        branches: '**'
#        branches: 'master'
        tags: '' # Restrict to blank tags
    pull_request:

jobs:
 dockerpi:
    name: Raspbian Buster pi Docker
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
        clean: false
    - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - run: docker run -i -v "${PWD}/..:${PWD}/.." lebarsfa/pi:buster-for-codac /bin/bash -c "uname -a ; cat /etc/os-release ; cd ${PWD} && pwd && lsb_release -a ; mkdir build ; cd build && cmake -E env CXXFLAGS="-fPIC" CFLAGS="-fPIC" cmake -D INTERVAL_LIB=gaol -D CMAKE_INSTALL_PREFIX=../ibex .. && cmake --build . --config Release --target install && cd .. && sed -i "s/\\\\/home\\\\/runner\\\\/work\\\\/ibex-lib\\\\/ibex-lib\\\\/ibex/\\\\/usr\\\\/local/" ibex/share/ibex/cmake/*.cmake && zip -q -r ibex_armv6hf_buster.zip ibex && sudo cp -Rf ibex/* /usr/local/ && rm -Rf ibex && cd tests/test_ibex && cmake . && cmake --build . --config Release && file ./my_project && ./my_project"
    - uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "*.zip"
        overwrite: true
        tag_name: autotagname-${{ github.sha }}
      if: (github.event_name != 'pull_request')
